# Generated by Django 3.2.6 on 2021-08-18 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runbot', '0003_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savatcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runbot.furnitures')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runbot.profile')),
            ],
        ),
    ]
